services: mysql
language: php
php:
  - 7.0
  - 7.1
before_script:
  - composer install
  - cat "$TRAVIS_BUILD_DIR/config/my.cnf" | sudo tee -a /etc/mysql/my.cnf
  - sudo service mysql restart
  - wget https://phar.phpunit.de/phpunit.phar
script: composer test
